// Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

AWS_ACCOUNT_ID                         = "904233109241"
APP                                    = "mit"
ENV                                    = "snd"
AWS_PRIMARY_REGION                     = "us-east-1"
S3_KMS_KEY_ALIAS                       = "mit-snd-s3-secret-key"
INVENTORY_DATA_FILE                    = "s3://904233109241-mit-snd-finops-inventory-s3-glue-s3-target/initial-inventory-report.csv.gz"
GLUE_ROLE_NAME                         = "mit-snd-glue-role"
INVENTORY_DATA_SOURCE_BUCKET_NAME      = "904233109241-mit-snd-finops-inventory-s3-glue-s3-source"
INVENTORY_DATA_TARGET_BUCKET_NAME      = "904233109241-mit-snd-finops-inventory-s3-glue-s3-target"
INVENTORY_DATA_SOURCE_BUCKET           = "s3://904233109241-mit-snd-finops-inventory-s3-glue-s3-source/"
INVENTORY_DATA_TARGET_BUCKET           = "s3://904233109241-mit-snd-finops-inventory-s3-glue-s3-target/"
INVENTORY_ICEBERG_BUCKET               = "s3://904233109241-mit-snd-finops-inventory-s3-glue-s3-iceberg/"
GLUE_SPARK_LOGS_BUCKET                 = "s3://904233109241-mit-snd-glue-spark-logs/"
GLUE_TEMP_BUCKET                       = "s3://904233109241-mit-snd-glue-temp/"
GLUE_KMS_KEY_ALIAS                     = "mit-snd-glue-secret-key"
CLOUDWATCH_KMS_KEY_ALIAS               = "mit-snd-cloudwatch-secret-key"
EVENTBRIDGE_ROLE_NAME                  = "mit-snd-eventbridge-role"
GLUE_SCRIPTS_BUCKET_NAME               = "904233109241-mit-snd-glue-scripts"
