export APP_NAME="miw-sgml-iaac"
export AWS_ACCOUNT_ID="985167257817"
export AWS_DEFAULT_REGION="us-east-1"
export ENV_NAME="sbx"
export AWS_PRIMARY_REGION="us-east-1"
export AWS_SECONDARY_REGION="us-east-1"
export TF_S3_BACKEND_NAME="minerva-miw-sgml-poc"