export APP_NAME="abhi"
export AWS_ACCOUNT_ID="633391536196"
export AWS_DEFAULT_REGION="us-east-1"
export ENV_NAME="snd"
export AWS_PRIMARY_REGION="us-east-1"
export AWS_SECONDARY_REGION="us-west-2"
export TF_S3_BACKEND_NAME="sowj"