export APP_NAME="miw"
export AWS_ACCOUNT_ID="904233109241"
export AWS_DEFAULT_REGION="us-east-1"
export ENV_NAME="snd"
export AWS_PRIMARY_REGION="us-east-1"
export AWS_SECONDARY_REGION="us-west-2"
export TF_S3_BACKEND_NAME="sndlh"